### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by rileybona** [rileybona/sharesage#28]
Get readme up to 'green lit' standards

**Comment by rileybona** [comment]
Tech stack, gif / vid navigating the page, future implementations, technical implementation examples, contact links

**Comment by rileybona** [comment]
just about done ! Missing david's LinkedIn & vid gifs

**Comment by TheCyberLocal** [comment]
I've finished the tech stack. I'm waiting on David for his LinkedIn profile link and I can't do gifs until the website styling is finished.

**Comment by TheCyberLocal** [comment]
I'm going to close this issue and update the issue I created for David to include adding his LinkedIn to the readme whenever he has time to create it.
