### ISSUE TITLE
Decide on Dashboard page

### ISSUE THREAD

**Issue by rileybona** [rileybona/sharesage#34]
option 1: 

- 'you owe John $4.22" [links to expense] 
- 'Penny owes you $12.42' [links to expense]

option 2: 
- the weather (or cute animation or something equally useless)

option 3 
- delete this page and '/' to all expenses

**Comment by rileybona** [comment]
/ implement dashboard page lol

**Comment by daviiiL** [comment]
make the dashboard into author info boards
